### ISSUE TITLE
Google Drive template missing

### ISSUE THREAD

**Issue by arguiot** [primer/presentations#46]
The google drive link for templates isn't public, so we can't download the Keynote and PowerPoint templates

**Comment by ashygee** [comment]
Hi @arguiot the templates have been created for GitHub team members to use for internal and GitHub associated presentations so they aren't available to the public. As they are a part of Primer, we have made the documentation available for the public to view but actual usage is GitHub use only at this time. Sorry for any confusion or frustration this has caused.

**Comment by arguiot** [comment]
Oh, ok. It would have been really cool to have a GitHub style presentation template, but anyway... could you add a little banner saying that it’s not available to the public? Because it was really confusing 😊
