### ISSUE TITLE
Dead link to the illustration assets

### ISSUE THREAD

**Issue by jeffwilcox** [primer/presentations#53]
Hi,
On the page at https://primer.style/presentations/design-guidelines, the referenced URL to https://primer.style/presentations/presentations/docs/assets for the assets 404s...

Is this stored on Google Drive somewhere instead?

**Comment by jeffwilcox** [comment]
So thinking the modern guidance is just to point people at ghicons or octicons, but yeah, link's still dead :)

**Comment by yaili** [comment]
Thanks for submitting, @jeffwilcox :)

I have a PR queued now that should fix it.
