### ISSUE TITLE
Google Slide Template out of date (2019)

### ISSUE THREAD

**Issue by i-marsh** [primer/presentations#55]
When creating a new google slide presentation from the google templates, the title slide defaults to 2019.

![image](https://user-images.githubusercontent.com/35036892/82042051-37d1ea80-9677-11ea-8df7-c01ea75a62f3.png)
---
Suggested fix ... update to 2020 :) or to auto-text for current year `yyyy`

**Comment by ashygee** [comment]
This has been fixed. The date has been removed and the `Subtitle` section now only reads "GitHub".

![image](https://user-images.githubusercontent.com/10384315/82072338-6e663000-968c-11ea-9d65-7aa11f11df2a.png)
